server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_jwt
    password: Knaapje999
    username: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect